# logger, to see logback-spring.xml
logging.level: INFO
logging.level.app: DEBUG

# server application
spring.application.name: =artifactId=
spring.mvc.favicon.enabled: false

server.port: 11000
server.use-forward-headers: true
server.tomcat.protocol_header: X-Forwarded-Proto
server.tomcat.remote_ip_header: X-Forwarded-For
server.tomcat.port-header: X-Forwarded-Port

belost.path: /web/github.io/belost.xyz
